export const pokemonActionTypes = {
  LIST_POKEMON_REQUEST: 'LIST_POKEMON_REQUEST',
  LIST_POKEMON_SUCCESS: 'LIST_POKEMON_SUCCESS',
  LIST_POKEMON_FAIL: 'LIST_POKEMON_FAIL',
  //
  DETAILS_POKEMON_REQUEST: 'DETAILS_POKEMON_REQUEST',
  DETAILS_POKEMON_SUCCESS: 'DETAILS_POKEMON_SUCCESS',
  DETAILS_POKEMON_FAIL: 'DETAILS_POKEMON_FAIL',
};
